export const WORDS_D = [
  'DADDY', 'DAILY', 'DAIRY', 'DAISY', 'DALLY', 'DANCE', 'DANDY', 'DATUM', 'DAUNT', 'DEALT',
  'DEATH', 'DEBAR', 'DEBIT', 'DEBUG', 'DEBUT', 'DECAL', 'DECAY', 'DECOR', 'DECOY', 'DECRY',
  'DEFER', 'DEIGN', 'DEITY', 'DELAY', 'DELTA', 'DELVE', 'DEMON', 'DEMUR', 'DENIM', 'DENSE',
  'DEPOT', 'DEPTH', 'DERBY', 'DETER', 'DETOX', 'DEUCE', 'DEVIL', 'DIARY', 'DICEY', 'DIGIT',
  'DILLY', 'DIMLY', 'DINER', 'DINGO', 'DINGY', 'DIODE', 'DIRGE', 'DIRTY', 'DISCO', 'DITCH',
  'DITTO', 'DITTY', 'DIVAN', 'DIVER', 'DIVOT', 'DIZZY', 'DODGE', 'DODGY', 'DOGMA', 'DOING',
  'DOLLY', 'DONOR', 'DONUT', 'DOPEY', 'DORSE', 'DOSER', 'DOTER', 'DOTTY', 'DOUBT', 'DOUGH',
  'DOWDY', 'DOWEL', 'DOWNY', 'DOWRY', 'DOWSE', 'DOYEN', 'DOZEN', 'DRAIN', 'DRAKE', 'DRAMA',
  'DRANK', 'DRAPE', 'DRAWL', 'DRAWN', 'DREAD', 'DREAM', 'DRESS', 'DRIED', 'DRIER', 'DRIES',
  'DRIFT', 'DRILL', 'DRILY', 'DRINK', 'DRIVE', 'DROLL', 'DRONE', 'DROOL', 'DROOP', 'DROSS',
  'DROVE', 'DROWN', 'DRUID', 'DRUNK', 'DRYER', 'DRYLY', 'DUCAL', 'DUCHY', 'DUCKS', 'DUCTS',
  'DUDDY', 'DUELS', 'DUETS', 'DUFFS', 'DUKES', 'DULLS', 'DULLY', 'DUMBS', 'DUMPS', 'DUMPY',
  'DUNCE', 'DUNES', 'DUNGS', 'DUNKS', 'DUNNY', 'DUPED', 'DUPER', 'DUPES', 'DURED', 'DURES',
  'DURNS', 'DUROC', 'DUROS', 'DURRA', 'DURRS', 'DURRY', 'DURST', 'DURUM', 'DUSKS', 'DUSKY',
  'DUSTS', 'DUSTY', 'DUTCH', 'DUVET', 'DUXES', 'DWALE', 'DWALM', 'DWAMS', 'DWANG', 'DWARF',
  'DWEEB', 'DWELL', 'DWELT', 'DWILE', 'DWINE', 'DYADS', 'DYERS', 'DYING', 'DYKED', 'DYKES',
  'DYKEY', 'DYKON', 'DYNEL', 'DYNES'
]

