export const WORDS_I = [
  'IAMBS', 'IATRY', 'IBRIK', 'ICERS', 'ICHED', 'ICHES', 'ICHOR', 'ICIER', 'ICILY', 'ICING',
  'ICKER', 'ICKLE', 'ICONS', 'ICTAL', 'ICTIC', 'ICTUS', 'IDANT', 'IDEAL', 'IDEAS', 'IDEES',
  'IDENT', 'IDIOM', 'IDIOT', 'IDLER', 'IDLES', 'IDOLA', 'IDOLS', 'IDYLS', 'IFTAR', 'IGAPO',
  'IGGED', 'IGLOO', 'IGLUS', 'IGNIS', 'IHRAM', 'IKANS', 'IKATS', 'IKONS', 'ILEAC', 'ILEAL',
  'ILEUM', 'ILEUS', 'ILIAC', 'ILIAD', 'ILIAL', 'ILIUM', 'ILLER', 'ILLTH', 'IMAGE', 'IMAGO',
  'IMAMS', 'IMARI', 'IMAUM', 'IMBED', 'IMBUE', 'IMIDE', 'IMIDO', 'IMIDS', 'IMINE', 'IMINO',
  'IMMEW', 'IMMIT', 'IMMIX', 'IMPED', 'IMPEL', 'IMPIS', 'IMPLY', 'IMPOT', 'IMPRO', 'IMSHI',
  'IMSHY', 'INANE', 'INAPT', 'INARM', 'INBYE', 'INCEL', 'INCLE', 'INCOG', 'INCUR', 'INCUS',
  'INCUT', 'INDEW', 'INDEX', 'INDIA', 'INDIE', 'INDOL', 'INDOW', 'INDRI', 'INDUE', 'INEPT',
  'INERM', 'INERT', 'INFER', 'INFIX', 'INFOS', 'INFRA', 'INGAN', 'INGLE', 'INGOT', 'INION',
  'INKED', 'INKER', 'INKLE', 'INLAY', 'INLET', 'INNED', 'INNER', 'INNIT', 'INORB', 'INPUT',
  'INRUN', 'INSET', 'INSPO', 'INTEL', 'INTER', 'INTIL', 'INTIS', 'INTRA', 'INTRO', 'INULA',
  'INURE', 'INURN', 'INUST', 'INVAR', 'INWIT', 'IODIC', 'IODID', 'IODIN', 'IONIC', 'IOTAS',
  'IPPON', 'IRADE', 'IRATE', 'IRIDS', 'IRING', 'IRKED', 'IROKO', 'IRONE', 'IRONS', 'IRONY',
  'ISBAS', 'ISHES', 'ISLED', 'ISLES', 'ISLET', 'ISNAE', 'ISSEI', 'ISSUE', 'ISTLE', 'ITCHY',
  'ITEMS', 'ITHER', 'IVIED', 'IVIES', 'IVORY', 'IXIAS', 'IXNAY', 'IXORA', 'IXTLE', 'IZARD',
  'IZARS', 'IZZAT'
]

